name: txqr_app
description: "TXQR - Transfer files via animated QR codes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.2
  share_plus: ^10.1.4
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
